### PR TITLE
fix: return 500 error when an uncaught error occurs in async handler

### PR DESCRIPTION
**Pull request by zaggino**
hi,
we've had problems with using this, because you forgot to `reply(...)` with the error so methods were left hanging and timing out ... this fixes that issue

### CODE REVIEW

**Comment by zaggino** [comment]
pushed, @ide take a look again

**Comment by ide** [comment]
Great, thank you @zaggino =)

**Comment by zaggino** [comment]
No worries, ping me when you publish this to the npm please :)

**Comment by ide** [comment]
Published as 1.0.1

**Comment by zaggino** [comment]
:+1:

**Pull request merged**
