### PR TITLE
typo: add missing colon in README

### PR DESCRIPTION
**Pull request by VitoVan**
Am I wrong? 

I feel shocked that no one talk about this.

A MISSING COLON??

### CODE REVIEW

**Comment by ide** [comment]
The README is correct, we want this to be an async function.

**Comment by VitoVan** [comment]
Sorry, I didn't get it.

```javascript
handler: { async async(request, reply) {} }
```

or this ?

```javascript
handler: { async: async(request, reply) {} }
```

The second example https://github.com/ide/hapi-async-handler#using-co **do have a colon** after word `async`:

### Using co

You can also use co and generator functions without any source-code transformations:

```javascript
server.route({
  method: 'GET',
  path: '/',
  handler: {
    // co.wrap creates a function that returns a promise, just like an async function
    async: co.wrap(function*(request, reply) {
      require('instapromise');
      var fileContents = yield fs.promise.readFile('example.txt', 'utf8');
      reply(fileContents);
    }),
  },
});
```

**Comment by VitoVan** [comment]
And also in the test: 

https://github.com/ide/hapi-async-handler/blob/master/test/handler.js#L99

```javascript
  function registerDefaultAsyncHandler(server, handler) {
    server.route({
      method: 'GET',
      path: '/',
      handler: {
        async: handler,
      },
      config: {
        timeout: {
          server: 1000,
        },
      },
    });
  }
});
```

**Comment by ide** [comment]
Both are correct, I recommend reading up on JavaScript syntax up to ES2017 to clear up your confusion.

**Comment by VitoVan** [comment]
OK, thank you very much, I am checking that, sorry to bother.

**Comment by VitoVan** [comment]
OH!!!!!! I KNOW IT NOW!!!

```javascript
handler: { async async(request, reply) {} }
```

is the same as 

```javascript
const async = async (request, reply) => {};
handler: { async }
```

and in `handler: { async async(request, reply) {} }`, the first `async` is as the keyword in `async/await` and the second one is treated as the `key` in `handler`.

What a Syntactic sugar!

**Pull request closed without merging**
