### PR TITLE
Fixes #6

### LINKED ISSUE #6: Bind does not work
http://hapijs.com/api#serverbindcontext

### PR DESCRIPTION
**Pull request by grabbou**

### CODE REVIEW

**Comment by ide** [comment]
Thanks!

**Comment by ide** [comment]
I won't be at my computer with this code for awhile but I'll push a new version to npm later today.

**Comment by grabbou** [comment]
No worries ;) Thanks a lot!

**Comment by ide** [comment]
1.0.3 is now on npm

**Pull request merged**
